### PR TITLE
Improved travis config

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by jeremeamia** [comment]
Would love an explanation about these changes. :-)

**Comment by GrahamCampbell** [comment]
One sec while I find a previous pull request I made very recently...

**Comment by GrahamCampbell** [comment]
https://github.com/mtdowling/cron-expression/pull/75

The changes I've made here to super closure are essentially the same. :)

**Comment by GrahamCampbell** [comment]
Oh yeh, and `--dev` is default so we don't need to specify it.

**Pull request merged**
