### PR TITLE
No longer allow php 7.0 to fail

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
NB, it's currently failing.

```
There were 2 failures:
1) SuperClosure\Test\Unit\SerializableClosureTest::testUnserializationFailsIfClosureCorrupt
Failed asserting that exception of type "ParseError" matches expected exception "SuperClosure\Exception\ClosureUnserializationException".
2) SuperClosure\Test\Integ\SerializationTest::testSerializeStaticClosure
Failed asserting that 'ERROR' matches expected 10.
/home/travis/build/jeremeamia/super_closure/tests/Integ/SerializationTest.php:181
/home/travis/build/jeremeamia/super_closure/tests/Integ/SerializationTest.php:146
```

**Comment by GrahamCampbell** [comment]
https://github.com/jeremeamia/super_closure/pull/71 fixed the first issue.

**Comment by GrahamCampbell** [comment]
Still getting:

```
There was 1 failure:
1) SuperClosure\Test\Integ\SerializationTest::testSerializeStaticClosure
Failed asserting that 'ERROR' matches expected 10.
/home/travis/build/jeremeamia/super_closure/tests/Integ/SerializationTest.php:181
/home/travis/build/jeremeamia/super_closure/tests/Integ/SerializationTest.php:146
```

**Comment by jeremeamia** [comment]
That means something in PHP7 or PhpParser 2 is causing an error during unserialization with this use case: https://github.com/jeremeamia/super_closure/blob/master/tests/Integ/SerializationTest.php#L139-L146

**Comment by GrahamCampbell** [comment]
We, we're still running the tests using php parser 1.x atm.

**Comment by jeremeamia** [comment]
We'll have to debug what error is happening. I have no time to do this, and may not for a while. If I somehow find time, I'll report back here.

**Comment by GrahamCampbell** [comment]
Thanks. If I do get this fixed in the meanwhile, would you be able to release 2.2.0 at that point?

**Comment by GrahamCampbell** [comment]
Ok, we're passing here now. Ping @jeremeamia. Does my work around look ok? Looks like PHP 7 made a few changes to the reflection API while we weren't looking. :)

**Comment by jeremeamia** [comment]
- https://3v4l.org/aOOnS
- https://github.com/php/php-src/blob/php-7.0.0RC5/NEWS

**Comment by GrahamCampbell** [comment]
Ahhh, right. I'll change my "fix" then. :)

**Comment by GrahamCampbell** [comment]
@jeremeamia How does this look now then. :)

**Comment by jeremeamia** [comment]
Yup, that looks fine to me. Thanks. :+1:

**Comment by GrahamCampbell** [comment]
:D

**Pull request merged**
