### PR TITLE
CS fixes and cleanup

### PR DESCRIPTION
**Pull request by GrahamCampbell**
CS fixes originally generated by https://styleci-staging.grahamjcampbell.co.uk/commits/6e3d85600b6f6953aa6a5c3decafb50198c15d5a. I've been through the files again afterwards.

### CODE REVIEW

**Comment by jeremeamia** [comment]
Whoa... not sure I agree with all those style changes. Are you using [php-cs-fixer](http://cs.sensiolabs.org/)?

**Comment by GrahamCampbell** [comment]
Ish. Using a fork with custom config. See the styleci organisation on github.

**Comment by jeremeamia** [comment]
StyleCI looks like a cool project, btw! :smile:

My coding style is like the `php-cs-fixer` defaults, but without the `new_with_braces` fixer.

**Comment by GrahamCampbell** [comment]
We really need a no braces unless required fixer. There's no way to automatically revert these changes because of all the extra changes I've made afterwards. I'll take a look at this again soonish.

**Pull request closed without merging**
