### PR TITLE
Corrected usage of Composer to install the package

### PR DESCRIPTION
**Pull request by asgrim**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Both are fine.

**Comment by GrahamCampbell** [comment]
Could you update this to include both rather than removing a perfectly valid way to install it.

**Comment by asgrim** [comment]
@GrahamCampbell using `composer require` is the "best practice" method of installing packages, thus should be encouraged by all responsible package maintainers.

**Comment by GrahamCampbell** [comment]
I'll make the change myself then. Thanks anyway. :)

**Pull request merged**
