### PR TITLE
Drop our custom hash_equals for symfony/polyfill-php56

### PR DESCRIPTION
**Pull request by GrahamCampbell**
What do you think @jeremeamia?

### CODE REVIEW

**Comment by jeremeamia** [comment]
looking

**Comment by jeremeamia** [comment]
@GrahamCampbell I don't see much value in switching, especially since it adds 2 new dependencies (in theory—seems like Symfony and Laravel users might already have them anyway). Any reasons why you think we should be compelled to make this change?

**Comment by GrahamCampbell** [comment]
It makes sense from a security perspective. We're allowing symfony to maintain that security critical function. Symfony's polyfill packages will become widely used to deal with this sort of thing.

I do have another proposal then. How about we mark it as a "suggested" dependency in the composer.json, and then do a major version bump of super closure?

**Comment by jeremeamia** [comment]
Why a major version bump?

**Comment by GrahamCampbell** [comment]
Because it's a breaking change for PHP 5.5 users.

**Comment by GrahamCampbell** [comment]
https://github.com/jeremeamia/super_closure/pull/76

**Comment by jeremeamia** [comment]
I see... I think I prefer this PR then. No need for a version bump.

**Comment by jeremeamia** [comment]
Let's do it. :+1:

**Comment by GrahamCampbell** [comment]
Awesome. :)

**Pull request merged**
