### PR TITLE
Handle unserialization errors

### PR DESCRIPTION
**Pull request by CarsonF**
If `unserialize` fails or returns an object that isn't a `SuperClosure` PHP crashes with a fatal error with undefined method. This fixes that to just throw exception and not emit a notice.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmmmm, not sure we should do this, especially given the fact that in php 7 we can no catch the ParseError. What do you think @jeremeamia?

**Comment by GawainLynch** [comment]
This fix works for me in PHP 7-RC6…

**Comment by GrahamCampbell** [comment]
Yes, but it's not pretty, or even needed on php 7.=, because we can catch the error, rather than messing with the error handler.

**Comment by GawainLynch** [comment]
So the whole world should upgrade to PHP 7 now?

**Comment by GrahamCampbell** [comment]
No, I'm saying that maybe we shouldn't change this, and let the error happen on php 5.

**Comment by CarsonF** [comment]
Yes I agree it is messy. Thank goodness PHP 7 changes that. However, right now there is no error. It just returns false. False checks are annoying and not always possible, like if the unserialization happens in a library.

**Comment by GrahamCampbell** [comment]
Yeh. I'm just trying to think about all options. Maybe this is the best way. I guess we can just wait for what @jeremeamia thinks. :)

**Pull request merged**
